### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by almin1337** [Ryuk-C/Jetpack-Compose-Login-Sample#2]
Can you please check why does your app crashes on startup? Is everything fine with backend?

This is an error I get in AppModule.kt:29:
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found

It seems that it can't find base URL.

**Comment by Ryuk-C** [comment]
Hello,

These source codes belong to the login screen of a real project, and if you examine the build.gradle file, you may notice that the web service URLs are hidden. Sharing web service URLs can pose serious risks. (It gives direct access to a real and working database.) I wanted to share that there are very few Jetpack Compose projects on the internet. You can review the codes and technologies (like Jetpack Compose, Hilt, Retrofit, Flow, Kotlin Coroutines, etc). If you still need help, please write to me on Linkedin :)
